### ISSUE TITLE
[BUG] Backend: Error ketika Menjalankan BackEnd

### ISSUE THREAD

**Issue by ReyRizki** [d4a-jtk19-webdev/proyek3-reproduce#11]
**Deskripsi**
Ketika menjalankan BackEnd, BackEnd tidak berhasil berjalan walaupun sudah menjalankan service yang ada sebelumnya. Terdapat bug yaitu mengenai association di bagian postgres-database.

**Cara Reproduce**
Langkah-langkah untuk menemukan bug yang sama:
1. Checkout ke branch main
2. Jalankan service sesuai yang terdapat di dokumentasi
3. Lihat bug di bagian BackEnd

**Ekspektasi**
JIka association tidak bermasalah, maka seharusnya service BackEnd berjalan.

**Screenshots**
![image](https://user-images.githubusercontent.com/39304683/145163457-f9708416-f222-4933-ba02-da67febb516a.png)

**Environment**
 - OS: FerenOS 10.21

**Cara Perbaikan yang sudah Dicoba**
Comment bagian Perkuliahan dan Mahasiswa di file association.js

**Comment by fauh45** [comment]
Working on it!
