### ISSUE TITLE
[BUG] FrontEnd: A login error during development

### ISSUE THREAD

**Issue by larasras** [d4a-jtk19-webdev/proyek3-reproduce#12]
**Deskripsi**
Saat masuk ke http://akun.localhost:5000/login , ditemukan error yang menyatakan seperti gambar di bawah

**Cara Reproduce**
Langkah-langkah untuk menemukan bug yang sama:
1. Menjalankan frontend
2. Menjalankan keycloak dengan perintah
`standalone.bat -Djboss.http.port=14417 -Dk\keycloak.frontendUrl=http://akun.localhost:5000/keycloak-proxy/auth`
3. Menjalankan akun-keycloak-proxy
4. Menjalankan development-http-proxy
5. Login realm
6. Menjalankan backend
7. Menjalankan service-monitoring
8. Login ke halaman http://akun.localhost:5000/login

**Ekspektasi**
Mengarahkan ke halaman http://akun.localhost:5000

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/61336325/145531847-27e1077d-ee5a-430a-89a4-f68e9a7f14eb.png">

**Environment**
 - OS: [Windows 10, Linux]
 - Browser [Chrome, Edge, Brave]

**Comment by gopelkujo** [comment]
Masalahnya ada pada langkah kedua yaitu menjalankan perintah yang salah.

1. Langkah pertama yang perlu dilakukan untuk memastikan keycloak sudah benar adalah mengekstraksi ulang keycloak.
2. Menjalankan langkah-langkah yang sama pada dokumentasi namun pada langkah 4b perintahnya diganti menjadi
`standalone.bat -Djboss.http.port=14417 -Dkeycloak.frontendUrl=http://akun.localhost:5000/keycloak-proxy/auth`
3. Lalu jalankan langkah-langkah selanjutnya sama seperti yang ada pada [dokumentasi](https://docs.google.com/document/d/1v5a5q5J9vXi8EXOCD8hZYcOYqQv14ekJCD5LsrpEmbI/edit?usp=sharing)

**Comment by larasras** [comment]
Alhamdulillah, bug-nya terselesaikan dengan solusi yang diberikan tersebut. 

Terimakasih banyak @gopelkujo
