### ISSUE TITLE
[BUG] FrontEnd: Auto refresh after login

### ISSUE THREAD

**Issue by alinrdinn** [d4a-jtk19-webdev/proyek3-reproduce#14]
**Deskripsi**
Sistem auto refresh setelah login menggunakan akun keycloak.

**Cara Reproduce**
Langkah-langkah untuk menemukan bug yang sama:
1. Jalankan seluruh sistem
2. Login ke dalam aplikasi menggunakan akun keycloack yang sudah ada
3. Setelah berada di salah page aplikasi, sistem akan otomatis me-refresh

**Ekspektasi**
Aplikasi menampilkan halaman sesuai URL-nya tanpa auto-refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/54460857/146004785-21128a58-d248-4a23-82e0-166eaf58aa26.png)

**Environment**
 - OS: [Windows 10, Linux]
 - Browser: [Chrome, Edge, Brave]

**Comment by FarraJessica** [comment]
Bug fixed close #14

**Comment by FarraJessica** [comment]
> Bug fixed close #14

Setelah di tracing, bug terjadi karena iframe yang terdapat pada file keycloak.js secara terus menerus dilakukan set interval, sehingga untuk mengatasi permasalahan tersebut perlu ditambahkan code `checkLoginIframe: false` pada setiap line code yang berisi parameter `onLoad: "login-required"`. Berdasarkan pengalaman saya, file yang terdapat kode tersebut adalah sebagai berikut :

1.  authentication.js
2. AbsensiMain.vue
3. Login.vue
4. ComponentTemplateMain.vue
5. monitoringmain.vue
6. PenilaianMain.vue
7. TemplateMain.vue

Sehingga, beberapa file di atas dimodifikasi untuk mengatasi bug yang ada.
